### ISSUE TITLE
ÔTridentÕ ??

### ISSUE THREAD

**Issue by isbkch** [tedivm/phpsessionmanager#2]
What does the "ÔTridentÕ" in strpos mean ?
And could you please explain why are we checking for "Trident" in the following:

``````
if ($userAgent != $httpUserAgent && !(strpos($_SERVER['HTTP_USER_AGENT'], ÔTridentÕ) !== false
            && strpos($_SERVER['HTTP_USER_AGENT'], ÔTridentÕ) !== false))
    {
        return false;
    }```
``````

**Comment by aidenxerror** [comment]
Look at the comment from September 1, 2009 at 6:39 pm here http://blog.teamtreehouse.com/how-to-create-bulletproof-sessions
